package com.jezz.es.entity;

import lombok.Data;
import lombok.NonNull;
import org.elasticsearch.action.DocWriteRequest;
import org.elasticsearch.action.support.WriteRequest;
import org.elasticsearch.common.unit.TimeValue;
import org.elasticsearch.common.xcontent.XContentType;
import org.elasticsearch.index.VersionType;

import java.util.Map;

@Data
public class IndexRequestPojo {
    private String type;
    @NonNull
    private String name;
    @NonNull
    private String id;
    private String routing;
    private Map<String,Object> source;
    private DocWriteRequest.OpType opType;
    private long version;
    private VersionType versionType;
    private XContentType contentType;
    private String pipeline;
    private long autoGeneratedTimestamp;
    private boolean isRetry;
    private long ifSeqNo;
    private long ifPrimaryTerm;
    private TimeValue timeValue;
    private WriteRequest.RefreshPolicy refreshPolicy;
}
